// <auto-generated />
namespace RentARabla.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _20161102initial : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_20161102initial));
        
        string IMigrationMetadata.Id
        {
            get { return "201611021702191_20161102-initial"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
